install.packages("matrixStats", repos="http://cran.us.r-project.org")
install.packages("pkgbuild", repos="http://cran.us.r-project.org")
install.packages("ctsmr", repos = "http://ctsm.info/repo/dev")
install.packages("tidyr",  repos="http://cran.us.r-project.org")
install.packages("progress", repos="http://cran.us.r-project.org")
install.packages("xtable", repos="http://cran.us.r-project.org")
install.packages("remotes", repos="http://cran.us.r-project.org")
remotes::install_github("INWT/mctools")
remotes::install_github("s-u/unixtools")
